### ISSUE TITLE
Erro no retorno (Sucesso) do envio de e-mail

### ISSUE THREAD

**Issue by mauriciovilela** [thrust-bitcodes/mail#1]
O bit code está enviando o e-mail com sucesso, porém a função está retornando "undefined".
Versão Thrust: 4.3-1
Versão bitcode email: última

**Comment by Brunomachadob** [comment]
A API não especifíca que é retornada uma confirmação de envio, se você viu isso em algum lugar, favor nos informar onde para que possamos remover a referência.
